// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.3

package api

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type AntennaHTTPServer interface {
	ListAntenna(context.Context, *ListAntennaRequest) (*ListAntennaReply, error)
}

func RegisterAntennaHTTPServer(s *http.Server, srv AntennaHTTPServer) {
	r := s.Route("/")
	r.GET("/antennas", _Antenna_ListAntenna0_HTTP_Handler(srv))
}

func _Antenna_ListAntenna0_HTTP_Handler(srv AntennaHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAntennaRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.Antenna/ListAntenna")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAntenna(ctx, req.(*ListAntennaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAntennaReply)
		return ctx.Result(200, reply)
	}
}

type AntennaHTTPClient interface {
	ListAntenna(ctx context.Context, req *ListAntennaRequest, opts ...http.CallOption) (rsp *ListAntennaReply, err error)
}

type AntennaHTTPClientImpl struct {
	cc *http.Client
}

func NewAntennaHTTPClient(client *http.Client) AntennaHTTPClient {
	return &AntennaHTTPClientImpl{client}
}

func (c *AntennaHTTPClientImpl) ListAntenna(ctx context.Context, in *ListAntennaRequest, opts ...http.CallOption) (*ListAntennaReply, error) {
	var out ListAntennaReply
	pattern := "/antennas"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.Antenna/ListAntenna"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
